controllers:
  resource: ../src/Shared/Infrastructure/Controller/
  type: annotation

main_company_controllers:
  resource: ../src/Company/Infrastructure/Controller/
  type: annotation

kernel:
  resource: ../src/Shared/Infrastructure/Kernel.php
  type: annotation

gesdinet_jwt_refresh_token:
  path: /api/auth/token/refresh

api_login_check:
  path: /api/auth/token/login

graphqlite_bundle:
  resource: '@GraphQLiteBundle/Resources/config/routes.xml'

overblog_graphiql_endpoint:
  resource: "@OverblogGraphiQLBundle/Resources/config/routing.xml"
