services:
  _defaults:
    autowire: true

  App\Shared\Infrastructure\Bus\CommandBus:
    public: true

  App\Shared\Infrastructure\Bus\QueryBus:
    public: true

  App\Shared\Infrastructure\Bus\EventBus:
    public: true
